### ISSUE TITLE
feature request: less restrictions on master password

### ISSUE THREAD

**Issue by magnetophon** [vitiral/novault#11]
Hi,

Thanks for this nice little program!

Would it be possible to remove the restriction in lenght on the master password?
I have a phrase that is easy to remember, but long, and if I cut it off, I'll have to remember where I cut it off....

Thanks!

**Comment by vitiral** [comment]
I have stopped using the manager personally, so you probably want to fork it if you wish to have additional features.

However, I'm not sure I agree with this utility. Adding additional characters is not useful for security, and I sincerely doubt it is actually useful for easy memory

**Comment by magnetophon** [comment]
I suspected you stopped using it.
I guess that makes all my issues irrelevant.

What are you using now?
IOW: can you recommend anything with similar features?

**Comment by vitiral** [comment]
I recently got a job at google and do all of my programming on my work laptop, so I just use chrome to manage my passwords. It's not my favorite, but I it makes my life a little easier for the time being.

Eventually I might go back to using novault, but not for a few years probably

**Comment by magnetophon** [comment]
OK, thanks.
