### ISSUE TITLE
feature request: ask for confirmation while creating master password

### ISSUE THREAD

**Issue by magnetophon** [vitiral/novault#12]
Any program that lets you set up a password should do this imho, but especially a pw-manager, with a pw that is (or at least should be) long.

**Comment by vitiral** [comment]
I intentionally did not support this because the workflow is:

- novault init
- novault loop

In this way, it already is a "confirmation". You won't be able to log in to add a single password :D

**Comment by magnetophon** [comment]
Good point, thanks!

**Comment by vitiral** [comment]
no problem!
